name: CICD-pipeline-for-VPS

on:
  push:
    branches:
      - master
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSH_KEY }}
      with:
        source: "."
        target: "/var/www/it-dev.tech/html"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSH_KEY }}
        script: cd /var/www/it-dev.tech/html; ls
        
