name: CICD-pipeline-for-VPS

on:
  push:
    branches:
      - master
      
jobs: 
  my_ci_part:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v1
     - name: Copy file via SCP
       uses: appleboy/ssh-action@v0.1.2
       with:
        host     : ${{ secrets.HOST }}
        username : ${{ secrets.USERNAME }}
        key      : ${{ secrets.SSH_KEY }}
        
        script: |
          ssh-keyscan -H ${{ secrets.HOST }} > ~/.ssh/known_hosts
          rm /var/www/it-dev.tech/html/index.html 
          git clone git@github.com:gokunull/testdeployment.git
          echo "Deployment complete succsessfully"
