name: CICD-pipeline-for-VPS

on:
  push:
    branches:
      - master
      
jobs: 
  my_ci_part:
    runs-on: ubuntu-latest
    
    steps:
     - uses: actions/checkout@v1
     - name: Copy file via SCP
       uses: appleboy/scp-action@master
       with:
        host     : ${{ secrets.HOST }}
        username : ${{ secrets.USERNAME }}
        key      : ${{ secrets.SSH_KEY }}
        source: "folder"
        target: "/var/www/it-dev.tech/html"
